Sprint1
NikolaySamchuk/BeautyWorld pull request #1
Opened 2023-03-26 09:36 UTC by NikolaySamchuk

2023-03-30 07:19 UTC, euge-huge requested changes
Отличная работа!

Пришлось поискать, что можно улучшить и доработать))

Продолжай в том же духе =)

2023-03-30 07:19 UTC, euge-huge commented on CSS/fonts.css
`отлично`

Мне нравится твоя декомпофзиция на файлы и папки, это читаемо и удобно!

Но сами папки чаще принято называть с маленькой буквы (React небольшое исключение)

2023-03-30 07:19 UTC, euge-huge commented on index.html
> +                        </li>
`нужно поправить`

Элементы навигации можно отнести к элементам, количество которых может возрасти. Пока это выглядит так:

<img width="1161" alt="image" src="https://user-images.githubusercontent.com/58856916/227944804-e9a312de-046a-4d82-a9c8-709a9cf7066e.png">

Хочется увидеть, что-то более дружелюбное =)

Фиксировать размеры, не нужно.
Могут пригодиться свойства:
```
min-width: fit-content;
flex-wrap: wrap;
flex-grow: ...;
gap: ...px ...px;
```

2023-03-30 07:19 UTC, euge-huge commented on index.html
> +                <img src="./Images/Header/girl.png" alt="">
`можно лучше`

Можно попробовать доработать, чтобы можно было заменить картинку и ничего не сломать)

![image](https://user-images.githubusercontent.com/58856916/228754402-fbb6ffea-62e5-41a2-b886-fe80c0c87aa3.png)

2023-03-30 07:19 UTC, euge-huge commented on index.html
> +                            <img src="./Images/About/10947227_1920 1.png" alt="">
`нужно поправить`

Нужно попробовать ограничить картинку в размерах, чтобы можно было заменить на другую, и чтобы края были закруглены у любой картинки
 
![image](https://user-images.githubusercontent.com/58856916/228756176-513c2418-d514-4939-ae3e-cb15d5c9f92e.png)

2023-03-30 07:19 UTC, euge-huge commented on index.html
> +                    <div class="section__advantage">
`отлично`

Тут с переполнением все отлично, если элментов больше 3, то они идут в следующие строки, молодец!

2023-03-30 07:19 UTC, euge-huge commented on CSS/styles.css
> +}
`можно лучше`

Мне кажется, что отдельные классы для шрифта избыточен, я бы внес в класс .navigation__link

2023-03-30 07:19 UTC, euge-huge commented on CSS/styles.css
`если интересно`

Можно посмотреть стайл гайд здесь:
https://learn.javascript.ru/css-format

Более полезно обратить на порядок стилей в этом гайде (вырезка ниже):

Рекомендуется располагать свойства в следующем порядке:
Сначала положение элемента относительно других: position, left/right/top/bottom, float, clear, z-index.
Затем размеры и отступы: width, height, margin, padding…
Рамка border, она частично относится к размерам.
Общее оформление содержимого: list-style-type, overflow…
Цветовое и стилевое оформление: background, color, font…

2023-03-30 07:19 UTC, euge-huge commented on CSS/styles.css
> +    height: 78px;
`нужно поправить`

Футер по заданию должен прилипать к низу страницы, даже если контента не на всю высоту экрана.

![image](https://user-images.githubusercontent.com/58856916/228758668-36a5a218-e0de-4f1e-8859-36ab7b026110.png)

2023-03-31 11:36 UTC, NikolaySamchuk commented on index.html
> +                        </li>
Поправил

2023-03-31 11:36 UTC, NikolaySamchuk commented on index.html
> +                <img src="./Images/Header/girl.png" alt="">
Поправил

2023-03-31 11:37 UTC, NikolaySamchuk commented on index.html
> +                            <img src="./Images/About/10947227_1920 1.png" alt="">
Поправил

2023-03-31 11:46 UTC, NikolaySamchuk commented on CSS/styles.css
> +}
Так сделал потому, что данный блок navigation используется в header, в footer и в секции "Услуги и цены". Шрифт в каждой из секции отличный, поэтому стили шрифта по дефолту лежат в navigation__link (что соответствует шрифту в header), а доп. классами я меняю шрифты уже для остальных секций

2023-03-31 11:46 UTC, NikolaySamchuk commented on CSS/styles.css
> +    height: 78px;
Прилепил футер

2023-03-31 11:47 UTC, NikolaySamchuk commented on CSS/styles.css
Спасибо, изучим

2023-03-31 12:08 UTC, NikolaySamchuk commented on CSS/fonts.css
Хорошо, принял

2023-04-08 10:01 UTC, euge-huge approved these changes

2023-04-09 12:40 UTC, merged