Sprint2
NikolaySamchuk/BeautyWorld pull request #2
Opened 2023-04-02 17:04 UTC by NikolaySamchuk

Не успел сделать рефакторинг styles.scss  с использованием sass

2023-04-08 13:46 UTC, euge-huge requested changes
Работа отличная!

Замечаний почти нет, структура, декомпозиция, реализация - все выполнено хорошо!

Продолжай в том же духе)

2023-04-08 13:46 UTC, euge-huge commented on .gitignore
> +src/CSS
Можно package-lock.json сюда добавить, его тоже можно не таскать в коммиты каждый раз

2023-04-08 13:46 UTC, euge-huge commented on src/scss/_media.scss
> +    }
Чтобы выглядело проще и читалось лучше можно сделать так:
```
.header {
  &__logo,
  &__phone {...}

....
}
```

2023-04-08 13:46 UTC, euge-huge commented on src/scss/_media.scss
> +    }
Это касается всех блоков, которые ниже тоже

2023-04-08 13:46 UTC, euge-huge commented on src/scss/styles.scss
> +    #menuToggle {
Почему везде классы, а тут по id? Какая в этом идея?

2023-04-08 13:46 UTC, euge-huge commented on src/scss/styles.scss
> +    max-width: 350px;
Я бы добавил сюда  
  ```
    display: flex;
    flex-direction: column;
    flex: 1;
```

Чтобы сровнять высоту блоков.

2023-04-08 13:46 UTC, euge-huge commented on src/scss/styles.scss
> +    }
Можно добавить

```
 .btn {
        align-self: flex-start;
        margin-top: auto;
 }
```

Или что-то подобное, чтобы кнопка прилипла к низу.

![image](https://user-images.githubusercontent.com/58856916/230724488-8e3f5f84-6a91-47a7-8a33-473fe08fc34e.png)

2023-04-08 13:47 UTC, euge-huge approved these changes

2023-04-09 12:44 UTC, merged

2023-04-16 11:48 UTC, NikolaySamchuk commented on .gitignore
> +src/CSS
исправил

2023-04-16 11:48 UTC, NikolaySamchuk commented on src/scss/_media.scss
> +    }
исправил

2023-04-16 11:48 UTC, NikolaySamchuk commented on src/scss/styles.scss
> +    #menuToggle {
исправил

2023-04-16 11:56 UTC, NikolaySamchuk commented on src/scss/styles.scss
> +    max-width: 350px;
так высота блоков одинакова. Не понял вашего замечания

2023-04-16 12:01 UTC, NikolaySamchuk commented on src/scss/styles.scss
> +    }
исправил